{"name": "test_invalid_credentials[edge]", "status": "passed", "description": "Test case for invalid Login credentials.", "attachments": [{"name": "stdout", "source": "58c281a2-6e3f-4f85-80ed-1bd63ecb5935-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "driver_setup", "value": "'edge'"}], "start": 1745668643731, "stop": 1745668648760, "uuid": "e6de7600-d86e-4841-86c9-04fc7d95a523", "historyId": "a990e0960df6e74856be76c66f8e2554", "testCaseId": "ef7373e7d568430ffce9b3d52770a421", "fullName": "tests.test_login.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('driver_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-EQTA2OP"}, {"name": "thread", "value": "7632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}