{"name": "test_invalid_credentials[edge]", "status": "passed", "description": "Test case for invalid Login credentials.", "attachments": [{"name": "stdout", "source": "ececf49e-e9b6-4f42-8b28-51f23f286f1f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "driver_setup", "value": "'edge'"}], "start": 1745668628060, "stop": 1745668639335, "uuid": "8f81358c-ee96-454e-b89a-18c7afe5e288", "historyId": "a990e0960df6e74856be76c66f8e2554", "testCaseId": "ef7373e7d568430ffce9b3d52770a421", "fullName": "tests.test_login.TestLogin#test_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('driver_setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-EQTA2OP"}, {"name": "thread", "value": "24292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}